; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32UDPWS_RX_CAM0]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP_WS
        -D CAM_ID=0
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32UDPWS_RX_CAM1]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP_WS
        -D CAM_ID=1
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32UDPWS_RX_CAM2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP_WS
        -D CAM_ID=2
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32UDPWS_RX_CAM3]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP_WS
        -D CAM_ID=3
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3


[env:esp32TALLYHUB_RX]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = 192.168.0.104
espota_port = 3232
build_flags = 
        -D MODE_RX_TALLYHUB_ESP32
        -D LED_PIN=5
        -D LED_COUNT=1
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        bblanchon/ArduinoJson@^7.0.4
        https://github.com/tzapu/WiFiManager.git
        links2004/WebSockets@^2.7.3